### ISSUE TITLE
Test Failures on fresh clone

### ISSUE THREAD

**Issue by CaptJakk** [keepkey/python-keepkey#77] opened 2019-10-17 17:50 UTC
```
TestMsgEthereumtxERC20_exch.test_cvc_to_ltc_exch
CallException: (9, u'/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error')

TestMsgEthereumtx_exch.test_eth_to_ltc_exch
CallException: (9, u'/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error')

TestMsgEthereumtx_exch.test_ethereum_exch_return_addr_error
AssertionError: '/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error'.endswith('Exchange withdrawal address error')

TestMsgEthereumtx_exch.test_ethereum_exch_withdrawal_cointype_error
AssertionError: '/kkemu/lib/firmware/signing.c:179:Exchange withdrawal address error'.endswith('Exchange withdrawal coin type error')

TestMsgGetaddress.test_ltc
CallException: (9, u'/kkemu/lib/firmware/fsm.c:147:Invalid coin name')

TestMsgGetaddress.test_ltc_m_address
CallException: (9, u'/kkemu/lib/firmware/fsm.c:147:Invalid coin name')

TestMsgSigntxExchange.test_btc_to_ltc_exchange
CallException: (9, 'Expected <ButtonRequest> (2 bytes):\ncode: ButtonRequest_SignExchange\n, got <Failure> (73 bytes):\ncode: Failure_Other\nmessage: "/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error"\n')

TestMsgSigntxExchange.test_ltc_to_eth_exchange
CallException: (9, 'Expected <TxRequest> (6 bytes):\nrequest_type: TXINPUT\ndetails {\n  request_index: 0\n}\n, got <Failure> (51 bytes):\ncode: Failure_Other\nmessage: "/kkemu/lib/firmware/fsm.c:147:Invalid coin name"\n')

TestMsgSigntxExchange.test_return_address_error
AssertionError: '/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error'.endswith('Exchange return address error')

TestMsgSigntxExchange.test_withdrawal_address_error
AssertionError: '/kkemu/lib/firmware/signing.c:174:Exchange withdrawal coin type error'.endswith('Exchange withdrawal address error')

TestMsgSigntxExchange.test_withdrawal_cointype_error
AssertionError: '/kkemu/lib/firmware/signing.c:179:Exchange withdrawal address error'.endswith('Exchange withdrawal coin type error')
```

**Comment by keepkeyjon** [comment] 2019-10-17 19:16
Which specific firmware & python-keepkey commits are you on respectively?

**Comment by keepkeyjon** [comment] 2019-12-10 00:23
can't reproduce. closing.

**Closed by keepkeyjon** 2019-12-10 00:23 UTC
